[window]
decorations = "Buttonless"
opacity = 0.80
# blur = true

[window.padding]
x = 2
y = 5

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
bold = { family = "JetBrainsMono Nerd Font", style = "Bold" }
italic = { family = "JetBrainsMono Nerd Font", style = "Italic" }
bold_italic = { family = "JetBrainsMono Nerd Font", style = "Bold Italic" }
size = 14.0

# Kanagawa Lotus Alacritty Colors

[colors.primary]
background = '#f2ecbc'
foreground = '#545464'

[colors.normal]
black = "#1f1f28"
red = "#c84053"
green = "#6f894e"
yellow = "#77713f"
blue = "#4d699b"
magenta = "#b35b79"
cyan = "#597b75"
white = "#545464"

[colors.bright]
black = "#8a8980"
red = "#d7474b"
green = "#6e915f"
yellow = "#836f4a"
blue = "#6693bf"
magenta = "#624c83"
cyan = "#5e857a"
white = "#43436c"

[colors.selection]
background = '#c9cbd1'
foreground = '#dcd7ba'

[[colors.indexed_colors]]
index = 16
color = '#e98a00'

[[colors.indexed_colors]]
index = 17
color = '#e82424'

# Kanagawa Wave Alacritty Colors

#[colors.primary]
#background = '#1f1f28'
#foreground = '#dcd7ba'
#
#[colors.normal]
#black = '#090618'
#red = '#c34043'
#green = '#76946a'
#yellow = '#c0a36e'
#blue = '#7e9cd8'
#magenta = '#957fb8'
#cyan = '#6a9589'
#white = '#c8c093'
#
#[colors.bright]
#black = '#727169'
#red = '#e82424'
#green = '#98bb6c'
#yellow = '#e6c384'
#blue = '#7fb4ca'
#magenta = '#938aa9'
#cyan = '#7aa89f'
#white = '#dcd7ba'
#
#[colors.selection]
#background = '#2d4f67'
#foreground = '#c8c093'
#
#[[colors.indexed_colors]]
#index = 16
#color = '#ffa066'
#
#[[colors.indexed_colors]]
#index = 17
#color = '#ff5d62'

