set -g status on
set -g status-position bottom

# Enable 24-bit (true color) support
set-option -g default-terminal "tmux-256color"
set-option -ga terminal-overrides ",xterm-256color:Tc"
# no bar background across entire width
set -g status-style "bg=default"

# small title on the left only
set -g status-left "#[bg=#183875,fg=#ffd45b] #[default]"

set -g status-right ""
setw -g window-status-current-style "bg=#183875,fg=#ffd45b"
setw -g window-status-current-format " #I:#W "
setw -g window-status-style "bg=#1c3b75,fg=yellow"
setw -g window-status-format " #I:#W "

